"""
Django settings for simpleWebAppl project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
gettext = lambda s: s

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
EXTERNAL_STATIC_DIR = os.path.join(BASE_DIR, 'externalStatic/')
EXTENDED_STATIC_DIR = os.path.join(BASE_DIR, 'extendedStatic/')
CMS_STATIC_DIR = os.path.join(BASE_DIR, 'cmsStatic/')
WEB_LAYOUT_DIR = os.path.join(BASE_DIR, 'webLayout/')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(7_91fa1zd+3-okluszgu0xsn@0@*^=+37=ua2&r-+!)f(rz@k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
SITE_ID = 1

ALLOWED_HOSTS = []
ADMIN_SITE_HEADER = "InfoTrophic Administration"

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'whoosh',
    'haystack',
    'storages',
#    'treebeard', 
#    'cms',  # django CMS itself
#    'mptt',  # utilities for implementing a tree
#    'menus',  # helper for model independent hierarchical website navigation
#    'sekizai',  # for javascript and css management
##    'filer',
####    'cmsplugin_filer_file',
##    'cmsplugin_filer_folder',
#    'cmsplugin_filer_image',
#    'cmsplugin_filer_teaser',
#    'cmsplugin_filer_video',
#    'djangocms_text_ckeditor',
    'simpleWebAppl',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
#    'django.middleware.doc.XViewMiddleware',
#    'cms.middleware.user.CurrentUserMiddleware',
#    'cms.middleware.page.CurrentPageMiddleware',
#    'cms.middleware.toolbar.ToolbarMiddleware',
#    'cms.middleware.language.LanguageCookieMiddleware',
)

ROOT_URLCONF = 'simpleWebAppl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                  os.path.join(PROJECT_DIR, 'templates'), EXTENDED_STATIC_DIR, 
                  os.path.join(WEB_LAYOUT_DIR, 'html'), 
                  os.path.join(EXTENDED_STATIC_DIR, 'SWextended/html'),
                  os.path.join(EXTENDED_STATIC_DIR, 'SWMaths/html'),
                  os.path.join(EXTENDED_STATIC_DIR, 'SWcms/html'), 
 		  os.path.join(CMS_STATIC_DIR, 'templates'),
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'django.core.context_processors.i18n',
                'django.core.context_processors.media',
                'django.core.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.request',
                #'sekizai.context_processors.sekizai',
                #'cms.context_processors.cms_settings',

            ],
        },
    },
]

WSGI_APPLICATION = 'simpleWebAppl.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'simpleWebDB.sqlite3'),
    }
}

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whooshSearchIndex'),
    },
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGES = [
    ('en', 'English'),
]

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

SE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT =  os.path.join(BASE_DIR,'static/')

STATICFILES_DIRS = (
    os.path.join(PROJECT_DIR, 'static'),
    EXTENDED_STATIC_DIR,
    EXTERNAL_STATIC_DIR,
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
#    'django.contrib.staticfiles.finders.DefaultStorageFinder',
)


CORS_ORIGIN_WHITELIST = (
    'google.com',
    'sagemath.org'
)

#AWS_STORAGE_BUCKET_NAME = 'infotrophic.com'
#AWS_ACCESS_KEY_ID = 'xxxxxxxxxxxxxxxxxxxx'
#AWS_SECRET_ACCESS_KEY = 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy'

# Tell django-storages that when coming up with the URL for an item in S3 storage, keep
# it simple - just use this domain plus the path. (If this isn't set, things get complicated).
# This controls how the `static` template tag from `staticfiles` gets expanded, if you're using it.
# We also use it in the next setting.
#AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

# This is used by the `static` template tag from `static`, if you're using that. Or if anything else
# refers directly to STATIC_URL. So it's safest to always set it.
#STATIC_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN

# Tell the staticfiles app to use S3Boto storage when writing the collected static files (when
# you run `collectstatic`).
#STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

'''
MIGRATION_MODULES = {
    'cms': 'cms.migrations_django',
    'menus': 'menus.migrations_django',
}


CMS_TEMPLATES = (
    ('template_1.html', 'Template One'),
    ('bookTemplate.html', 'Book Template'), 
#####    ('template_2.html', 'Template Two'),
)

CMS_PLACEHOLDER_CONF = {
    'content': {
        'name' : ('Content'),
        'plugins': ['TextPlugin', 'LinkPlugin'],
        'default_plugins':[
            {
                'plugin_type':'TextPlugin',
                'values':{
                    'body':'<p>Great websites : %(_tag_child_1)s and %(_tag_child_2)s</p>'
                },
                'children':[
                    {
                        'plugin_type':'LinkPlugin',
                        'values':{
                            'name':'django',
                            'url':'https://www.djangoproject.com/'
                        },
                    },
                    {
                        'plugin_type':'LinkPlugin',
                        'values':{
                            'name':'django-cms',
                            'url':'https://www.django-cms.org'
                        },
                    },
                ]
            },
        ]
    }
}
'''
CKEDITOR_SETTINGS = {
    'language': '{{ language }}',
    'toolbar_CMS': [
        ['Undo', 'Redo'],
        ['cmsplugins', '-', 'ShowBlocks'],
        ['Format', 'Styles'],
    ],
    'skin': 'moono',
}


